// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafaxdAnwN4-VgCE1RMwWkydniwlpyEi8',
    appId: '1:550072754782:web:e0ac1936a36d811d664acf',
    messagingSenderId: '550072754782',
    projectId: 'expense-calculator-91214',
    authDomain: 'expense-calculator-91214.firebaseapp.com',
    storageBucket: 'expense-calculator-91214.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhurNceJ5rXWb9ta3u6ysUzN1ymGSw88k',
    appId: '1:550072754782:android:12771206fd3ab161664acf',
    messagingSenderId: '550072754782',
    projectId: 'expense-calculator-91214',
    storageBucket: 'expense-calculator-91214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkx_KV7nAMiJ84r9lWJxtls1Ltq8EndHw',
    appId: '1:550072754782:ios:6e16153d2b99a12c664acf',
    messagingSenderId: '550072754782',
    projectId: 'expense-calculator-91214',
    storageBucket: 'expense-calculator-91214.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectSection2Group11',
  );

}